<a href="https://colab.research.google.com/github/Santosh-Gupta/NaturalLanguageRecommendations/blob/master/notebooks/data/DataGuideForGithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import h5py
import numpy as np
import pandas as pd

# Data for word2vec training on citations/references 

In [2]:
!gdown --id "1d68J1RCH3oA39iE5N0gvs1zN0iXQblBJ" 
h5file = h5py.File('SemanticScholar1p26M-CS-12-22-19.h5','r')
allData = np.column_stack(( h5file['paper' ][:] , h5file['cites' ][:] ))

Downloading...
From: https://drive.google.com/uc?id=1d68J1RCH3oA39iE5N0gvs1zN0iXQblBJ
To: /content/SemanticScholar1p26M-CS-12-22-19.h5
58.6MB [00:00, 124MB/s] 


# First column contains the embeddingID for a paper, and the 2nd column contains EmbeddingIDs for all of its reference and citation papers' embeddingIDs

In [3]:
allData

array([[235092,
        array([ 931311, 1018430,  523305,  822033,  529623,  938165,  927913],
      dtype=int32)],
       [868823, array([336997], dtype=int32)],
       [350063,
        array([ 153164,  395362,  294290,  189116,  178737,  847601,  528571,
        552113,  901146, 1071567,  439787], dtype=int32)],
       ...,
       [946513, array([  87528, 1252523, 1155882,  204501], dtype=int32)],
       [296967, array([953075, 913188, 307815], dtype=int32)],
       [35043, array([77923], dtype=int32)]], dtype=object)

In [4]:
allData[990]

array([181434, array([ 442775, 1151779], dtype=int32)], dtype=object)

In [5]:
allData[:,0].max()

1262995

In [6]:
allData.shape

(1262996, 2)

# Data for EmbeddingIds, Titles, Abstracts, and Semantic Scholar IDs

In [8]:
!gdown --id "1NyUQwgUNj9bFsiCnZ2TfKmWn5r-Y6wav" 

df = pd.read_json( 'TitlesIdsAbstractsEmbedIdsCOMPLETE_12-30-19.json.gzip', compression = 'gzip' )

Downloading...
From: https://drive.google.com/uc?id=1NyUQwgUNj9bFsiCnZ2TfKmWn5r-Y6wav
To: /content/TitlesIdsAbstractsEmbedIdsCOMPLETE_12-30-19.json.gzip
432MB [00:04, 93.3MB/s]


In [9]:
embed2Abstract = pd.Series(df['paperAbstract'].values,index=df['EmbeddingID']).to_dict()
embed2Abstract

{235092: 'This paper proposes simple analytic formulas for proportional-integral-derivative (PID) controller tuning for typical process models. The formulas are obtained in a similar way to the simple internal model control (SIMC) tuning rules, while the leading analysis is more delicate. Compared to SIMC counterparts, the new tuning formulas lead to better load disturbance rejection while giving similar setpoint response and peak sensitivity.',
 868823: 'Due to the advantages of high efficiency and high torque density, the Permanent Magnet Synchronous Machine (PMSM) has been widely used in direct-drive applications such as all-electric propulsion system. The loss and efficiency of PMSM are the main restriction for performance improvement. This paper focuses on analyzing the influence of structure parameters on the loss and efficiency of PMSM, including the split-ratio, the thickness of PMs, the pole-slot combination and the utilization of Halbach PM array, based on the Magnetic Circui

In [10]:
embed2Title = pd.Series(df['title'].values,index=df['EmbeddingID']).to_dict()
embed2Title

{235092: 'Simple analytic formulas for PID tuning',
 868823: 'Effect of structure parameters on the losses and efficiency of Surface-Mounted PMSM',
 350063: 'Saturated Throughput Analysis of IEEE 802.11ad EDCA For High Data Rate 5G-IoT Applications',
 664061: 'A Fuzzy Logic Algorithm for Minimizing Error (FLAME) in Wireless Sensor Networks',
 884696: 'FVF based CDTA and Its application',
 969635: 'Speech/music discrimination using awarped LPC-based feature and a fuzzy expert system for intelligent audio coding',
 418364: 'Effective Capacity for Renewal Service Processes With Applications to HARQ Systems',
 531667: 'Mashroom+: An Interactive Data Mashup Approach with Uncertainty Handling',
 1827: 'Robust Filtering for Markov Jump Systems by Randomized Algorithm Approach',
 506588: 'SSENet-2011: A Network Intrusion Detection System dataset and its comparison with KDD CUP 99 dataset',
 918081: 'On the Boundedness of Asymptotic Stability Regions for the Stochastic Theta Method',
 521881: '

In [11]:
embed2Paper = pd.Series(df['id'].values,index=df['EmbeddingID']).to_dict()
embed2Paper

{235092: '9488c6558185117bfcc80e5b2dcc01034aedd415',
 868823: 'a83855373be830ac0cf30787197d7fcd5e7d9b32',
 350063: '9eaeef8d82e7f052a1c6c7758003a0058b47d002',
 664061: '2d91f4bdaf10c1415813673be172c28b3d760fd1',
 884696: 'f36bc6011e08d32cfb1315460c9e21fa1a3c8a0c',
 969635: '89396b7d92dc9dab6a019d690433a93ba661d728',
 418364: '0f96a23930874831995b36b87e84d0f8baac8805',
 531667: '6b53e1b16fe61d06bbaf3bda008ba84208870e78',
 1827: '3048ff6081b15d142dec3de730c8cceb2ab493fa',
 506588: '31107dbcfab67cb3c34e2474fa5e872db22caff0',
 918081: '6a967dd4ab851b142e3bff57a99ef3b3e4ecc72f',
 521881: 'e2686fc68bb4418180f5fd05059bd75cbfb7ee95',
 724331: '5a30337cc37f4f4555cd99960c91fd3a669b40f7',
 1180684: '6acbb89c8c6c3cda55c6ac994c3f425448f133a5',
 395583: '028942f36b1355fb2742402e037458a3ff2f2fdc',
 961355: '5dd1d808a6d6cea4dc299bcb3f65657c28110bba',
 339728: '16d267fc23df533272b14d0c8e74eb4e905682fe',
 598708: 'e72b8bfe46e43253dc6b37b1cee0f931dfc50306',
 1113050: '948ba80dabfc20118e3317795e91bb8f36ea

In [12]:
inputEmbedId = 1232568

print('Title is : ' , embed2Title[inputEmbedId])
print('Abstract is : ' , embed2Abstract[inputEmbedId])
print('Link is :  https://www.semanticscholar.org/paper/' + embed2Paper[inputEmbedId])

Title is :  Is it possible to achieve the optimum throughput and fairness simultaneously in a MIMO Broadcast Channel?
Abstract is :  In this paper, a MIMO Broadcast Channel (MIMO-BC) with large (K) number of users is considered. It is assumed that all users have a hard delay constraint D. We propose a scheduling algorithm for maximizing the throughput of the system, while satisfying the delay constraint for all users. It is proved that by using the proposed algorithm, it is possible to achieve the maximum throughput and maximum fairness in the network, simultaneously, in the asymptotic case of K rarr infin. We introduce a new performance metric in the network, called "minimum average throughput", and prove that the proposed algorithm is capable of maximizing the minimum average throughput in a MIMO-BC, in the asymptotic case of K rarr infin. Finally, it is established that the proposed algorithm reaches the boundaries of the capacity region and stability region of the network, simultan