<a href="https://colab.research.google.com/github/Santosh-Gupta/NaturalLanguageRecommendations/blob/master/pruning_first_pass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd

In [0]:
import os
os.listdir('/content/gdrive/My Drive/text2doc_data')

['test_ignore',
 'med_data_all',
 'cs_data_english_only',
 'med_data_english_only']

In [0]:
fileTemp = '/content/gdrive/My Drive/text2doc_data/cs_data_english_only/' + 's2-cleaned-corpus-{:03}.json'
df = pd.read_json(fileTemp.format(4), orient='index')
df.head()

Sources3  ...    year
100089  ['DBLP']  ...  2010.0
100121  ['DBLP']  ...  2011.0
100189  ['DBLP']  ...  2000.0
10023         []  ...  1999.0
100380  ['DBLP']  ...  2013.0

[5 rows x 21 columns]

# Create a set up paperIDs. This will be used to filter out rows  that do not have a citation in the list 

In [0]:
fileTemp = '/content/gdrive/My Drive/text2doc_data/cs_data_english_only/' + 's2-cleaned-corpus-{:03}.json'
paperSet = set()

for i in range(179):
    if i%5==0:
        print(i)
    df = pd.read_json(fileTemp.format(i), orient='index')
    b = set(df['id'])
    paperSet.update(b)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175


In [0]:
len(paperSet)

1795148

# Remove any rows that does Not have a citation in the list of papers

In [0]:
# Prune and save

# saveTemp = gdrive_path + 'textPruned-{:03}.json'
fileTemp = '/content/gdrive/My Drive/text2doc_data/cs_data_english_only/' + 's2-cleaned-corpus-{:03}.json'

intermedTemp = 'firstP-{:03}.json'

for i in range(179):
    print(i)
    df = pd.read_json(fileTemp.format(i), orient='index')
    print(df.shape)
    #pruning removed rows that do not have a paper in the dictionary 
    df2 = df[df["totalCites2"].transform(lambda x: bool(set(x)&paperSet))] 
    df2.to_json( intermedTemp.format(i) )


0
(9912, 21)
1
(10177, 21)
2
(9911, 21)
3
(10244, 21)
4
(9993, 21)
5
(10204, 21)
6
(9998, 21)
7
(9994, 21)
8
(10230, 21)
9
(9745, 21)
10
(10248, 21)
11
(10077, 21)
12
(10059, 21)
13
(10016, 21)
14
(9880, 21)
15
(10180, 21)
16
(10076, 21)
17
(9941, 21)
18
(10049, 21)
19
(10029, 21)
20
(9945, 21)
21
(10206, 21)
22
(10106, 21)
23
(9940, 21)
24
(10001, 21)
25
(10021, 21)
26
(10035, 21)
27
(10093, 21)
28
(9932, 21)
29
(9998, 21)
30
(9831, 21)
31
(10038, 21)
32
(9925, 21)
33
(9945, 21)
34
(10121, 21)
35
(9932, 21)
36
(9829, 21)
37
(10008, 21)
38
(9879, 21)
39
(10008, 21)
40
(10072, 21)
41
(10028, 21)
42
(10097, 21)
43
(9960, 21)
44
(10034, 21)
45
(10159, 21)
46
(10048, 21)
47
(10009, 21)
48
(10132, 21)
49
(9947, 21)
50
(10066, 21)
51
(10016, 21)
52
(10060, 21)
53
(10023, 21)
54
(10071, 21)
55
(9861, 21)
56
(10141, 21)
57
(9950, 21)
58
(10056, 21)
59
(10094, 21)
60
(10013, 21)
61
(10005, 21)
62
(10017, 21)
63
(9982, 21)
64
(9834, 21)
65
(10059, 21)
66
(10164, 21)
67
(9939, 21)
68
(10169, 21)


# Create a new set of PaperIDs 

In [0]:
intermedTemp = 'firstP-{:03}.json'
paperSet = set()

for i in range(179):
    if i%5==0:
        print(i)
    df = pd.read_json(intermedTemp.format(i))
    b = set(df['id'])
    paperSet.update(b)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175


In [0]:
len(paperSet)

1262996

In [0]:
# Map a unique EmbeddingID for each paperID

In [0]:
paperID2EmbeddingID = {ni: indi for indi, ni in enumerate(paperSet)}
EmbeddingID2paperID = {indi: ni for indi, ni in enumerate(paperSet)}

In [0]:
len(paperID2EmbeddingID)

1262996

In [0]:
len(set(paperID2EmbeddingID))

1262996

In [0]:
len(set(EmbeddingID2paperID))

1262996

In [0]:
len(EmbeddingID2paperID)

1262996

In [0]:
paperID2EmbeddingID

# Save the paperID2EMbeddingID dictionary to your Gdrive. This will be used to retrieve papers from the EmbedID at inference

In [0]:
import json

# gdrive_path = ''
gdrive_path =  '/content/gdrive/My Drive/NaturalLanguageRecommendations/CS/' 

# Save paperID2EmbeddingID Dictionary to json
with open(gdrive_path+'paperID2EmbeddingID.json', 'w') as fp:
    json.dump(paperID2EmbeddingID, fp)



In [0]:
#Check if it saved correctly

import json

with open(gdrive_path+'paperID2EmbeddingID.json') as json_file:
    data = json.load(json_file)

# Open intermediate files and map the paperID's in the 'id' and citation columns to EmbeddingIDs. Save to 2nd intermediate file. You might want to save this to your gdrive account instead of on the colab instance, because there's a good chance the instance may crash due to running out of memory, and you may need to switch instances. 

In [0]:
# saveTemp = gdrive_path + 'textPruned-{:03}.json'

intermedTemp = 'firstP-{:03}.json'

# gdriveTemp = '/content/gdrive/My Drive/NaturalLanguageRecommendations/CS/firstPruneCorrected-{:03}.json'

intermedTemp2 = 'firstP2-{:03}.json'

# intermedTemp2 = '/content/gdrive/My Drive/NaturalLanguageRecommendations/CS/firstPruneCorrected-{:03}.json'

for i in range(179):
    dfAfterPruned = pd.read_json(intermedTemp.format(i))

    df3 = dfAfterPruned.assign(citEmebeddingIds=[[paperID2EmbeddingID[k] for k in row if paperID2EmbeddingID.get(k)] for row in dfAfterPruned["totalCites2"]])
    df3['EmbeddingID'] = df3['id'].map(paperID2EmbeddingID)
    # Save 
    df3[['EmbeddingID', 'paperAbstract', 'title', 'citEmebeddingIds']].to_json( intermedTemp2.format(i) )

In [0]:
EmbeddingID2paperID[33645]

'88e2bbd9b1b3113c88e8c3c60ae88b81e2da1807'

In [0]:
pd.set_option('max_colwidth', 800)


# Combine all dataframe files. You may not have enough RAM for this. If it crashes, you might get an option to restart in a higher RAM instance, which would be 25 gb in the CPU and GPU instances. If you saved the 2nd intermediate files in you Google drive, you can just start from this step. 

# If this crashes again, then you can switch to the TPU instance, and crash it. When you get the option for a higher ram instance, the TPU one will have 36 GB instead of 25 GB. If it crashes again, let me know, I'll alter the code to process one file at a time

In [0]:
afColl = []
for idx in range(179):
    if idx%5==0:
        print(idx)
    afColl.append( pd.read_json( intermedTemp2.format(idx) ) )

allDf = pd.concat(afColl)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175


In [0]:
allDf.shape

(1262996, 4)

In [0]:
# bb = set(allDf['EmbeddingID'])
# len(bb)

1262996

In [0]:
allDf

EmbeddingID  ...                                   citEmebeddingIds
100113       235092  ...  [931311, 1018430, 523305, 822033, 529623, 9381...
100534       868823  ...                                           [336997]
100756       350063  ...  [153164, 395362, 294290, 189116, 178737, 84760...
101147       664061  ...           [313973, 591548, 571510, 479610, 760686]
101286       884696  ...                            [970299, 8221, 1207310]
...             ...  ...                                                ...
996022       519998  ...                                  [383204, 1174990]
99698       1022390  ...                                          [1026226]
99709        946513  ...                  [87528, 1252523, 1155882, 204501]
9989         296967  ...                           [953075, 913188, 307815]
99984         35043  ...                                            [77923]

[1262996 rows x 4 columns]

# Reset the index, then delete the extra index column

In [0]:
allDf.reset_index(inplace =True)

In [0]:
del allDf['index']

In [0]:
allDf.head()

EmbeddingID  ...                                   citEmebeddingIds
0       235092  ...  [931311, 1018430, 523305, 822033, 529623, 9381...
1       868823  ...                                           [336997]
2       350063  ...  [153164, 395362, 294290, 189116, 178737, 84760...
3       664061  ...           [313973, 591548, 571510, 479610, 760686]
4       884696  ...                            [970299, 8221, 1207310]

[5 rows x 4 columns]

# Remove duplicates?

In [0]:
allDf.drop_duplicates(subset=['EmbeddingID'],  keep='first', inplace=True)

In [0]:
#check how many removed

allDf.shape

(1262996, 4)

# Create the HDF5 dataset

In [0]:
allNums = allDf[['EmbeddingID', 'citEmebeddingIds']]

In [0]:
import numpy as np

In [0]:
allNums['citEmebeddingIds'] = allNums['citEmebeddingIds'].apply(lambda x: np.array(x))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
numpyAll = allNums.values

In [0]:
numpyAll[0:10]

array([[235092,
        array([ 931311, 1018430,  523305,  822033,  529623,  938165,  927913])],
       [868823, array([336997])],
       [350063,
        array([ 153164,  395362,  294290,  189116,  178737,  847601,  528571,
        552113,  901146, 1071567,  439787])],
       [664061, array([313973, 591548, 571510, 479610, 760686])],
       [884696, array([ 970299,    8221, 1207310])],
       [969635, array([353121, 263616, 243836])],
       [418364,
        array([ 422597,  507650, 1258624,  936568,  612901,  418330, 1222164,
        391924, 1095247,   84533])],
       [531667, array([ 785602,  947367, 1256856])],
       [1827, array([ 809294, 1245639])],
       [506588, array([951349, 208114])]], dtype=object)

In [0]:
numpyAll[:,1]

array([array([ 931311, 1018430,  523305,  822033,  529623,  938165,  927913]),
       array([336997]),
       array([ 153164,  395362,  294290,  189116,  178737,  847601,  528571,
        552113,  901146, 1071567,  439787]),
       ..., array([  87528, 1252523, 1155882,  204501]),
       array([953075, 913188, 307815]), array([77923])], dtype=object)

In [0]:
np.max(numpyAll[:,0])

1262995

In [0]:
# np.max(numpyAll[:,0])

1262790

In [0]:
numpyAll[:,0].max()

1262995

In [0]:
len(numpyAll)

1262996

# Save to gdrive and delete allDf to save memory 

In [0]:
allDf[['EmbeddingID', 'paperAbstract', 'title']].to_json( '/content/gdrive/My Drive/NaturalLanguageRecommendations/CS/TitlesAbstractsEmbedIds.json.gzip', compression = 'gzip' )

In [0]:
del allDf

# Create and save HDF5 datateset

In [0]:
import h5py
h5f = h5py.File('/content/gdrive/My Drive/NaturalLanguageRecommendations/CS/SemanticScholarMed1p26M-CS-12-26-19.h5', 'w')
dt = h5py.special_dtype(vlen=np.dtype('int32'))

In [0]:
h5f.create_dataset('cites', data=numpyAll[:,1], dtype=dt, compression='gzip', compression_opts=9, chunks=True, maxshape=(None,) )
h5f.create_dataset('paper', data=numpyAll[:,0].astype(np.int32), compression='gzip', compression_opts=9, chunks=True, maxshape=(None,) )
h5f.close()